apiVersion: game.game.example.com/v1
kind: GameServerSet
metadata:
  name: hairpin-game
  namespace: default
spec:
  replicas: 2
  deleteDelaySeconds: 27
  template:
    metadata:
      labels:
        app: heritage-guide
    spec:
      containers:
      - name: pod
        image: nginx:alpine
        command: ["sleep", "infinity"]
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 16Mi
